# Basic Decision Tree for classification

## Imports

In [26]:
from sklearn import tree
import sklearn as sk
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import OneHotEncoder

import numpy as np
import pandas as pd

## Exploring the data

In [2]:
titanic_dataset = pd.read_csv("../../data/titanic/Titanic-Dataset.csv",index_col="PassengerId")
titanic_dataset.describe()

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [3]:
titanic_dataset.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
titanic_dataset.iloc[:5,:]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
titanic_dataset.dtypes

Survived      int64
Pclass        int64
Name         object
Sex          object
Age         float64
SibSp         int64
Parch         int64
Ticket       object
Fare        float64
Cabin        object
Embarked     object
dtype: object

## Naive approach

### Separating data into train and test

In [6]:
predictors, target = titanic_dataset.iloc[:, 1:], titanic_dataset.iloc[:, :1]
predictors_train, predictors_test, target_train, target_test = train_test_split(predictors, target, random_state=123)
target_train.head()

             Survived
PassengerId
661                 1
853                 0
704                 0
887                 0
526                 0

### Training tree clasifier model

In [7]:
clf = tree.DecisionTreeClassifier()
clf.fit(predictors_train, target_train)

ValueError: could not convert string to float: 'Frauenthal, Dr. Henry William'

### What happened
The error we are seeing is where sklearn is trying to convert a string value into a float.
Models tend to prefer a single type of input data. In our case, we have strings, floats and int datatypes.
What we should do is instead turn everything that we can into floats

## Less naive approach

### Preparing data

In [8]:
titanic_dataset_preprocessed = titanic_dataset.copy(deep=True)

In [9]:
titanic_dataset_preprocessed["Sex"] = (titanic_dataset_preprocessed["Sex"]=="male").astype("float64")

In [10]:
titanic_dataset_preprocessed.describe()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,0.383838,2.308642,0.647587,29.699118,0.523008,0.381594,32.204208
std,0.486592,0.836071,0.477990,14.526497,1.102743,0.806057,49.693429
min,0.000000,1.000000,0.000000,0.420000,0.000000,0.000000,0.000000
25%,0.000000,2.000000,0.000000,20.125000,0.000000,0.000000,7.910400
50%,0.000000,3.000000,1.000000,28.000000,0.000000,0.000000,14.454200
75%,1.000000,3.000000,1.000000,38.000000,1.000000,0.000000,31.000000
max,1.000000,3.000000,1.000000,80.000000,8.000000,6.000000,512.329200

In [11]:
titanic_dataset_preprocessed.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",1.0,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0.0,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",0.0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0.0,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",1.0,35.0,0,0,373450,8.0500,NaN,S

In [12]:
print("Number of unique ticket values: ", titanic_dataset_preprocessed["Ticket"].nunique())
print("Number of unique cabin values: ", titanic_dataset_preprocessed["Cabin"].nunique())
print("Number of unique embarked values: ",titanic_dataset_preprocessed["Embarked"].nunique())

Number of unique ticket values:  681
Number of unique cabin values:  147
Number of unique embarked values:  3

In [13]:
titanic_dataset_preprocessed = titanic_dataset_preprocessed.drop(["Name", "Ticket", "Cabin"], axis=1)

In [14]:
titanic_dataset_preprocessed

             Survived  Pclass  Sex   Age  SibSp  Parch     Fare Embarked
PassengerId
1                   0       3  1.0  22.0      1      0   7.2500        S
2                   1       1  0.0  38.0      1      0  71.2833        C
3                   1       3  0.0  26.0      0      0   7.9250        S
4                   1       1  0.0  35.0      1      0  53.1000        S
5                   0       3  1.0  35.0      0      0   8.0500        S
...               ...     ...  ...   ...    ...    ...      ...      ...
887                 0       2  1.0  27.0      0      0  13.0000        S
888                 1       1  0.0  19.0      0      0  30.0000        S
889                 0       3  0.0   NaN      1      2  23.4500        S
890                 1       1  1.0  26.0      0      0  30.0000        C
891                 0       3  1.0  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [15]:
titanic_dataset_preprocessed = pd.get_dummies(titanic_dataset_preprocessed).astype("Float64").dropna()

### Separating data into test and train

In [16]:
predictors, target = titanic_dataset_preprocessed.iloc[:, 1:], titanic_dataset_preprocessed.iloc[:, :1]
predictors_train, predictors_test, target_train, target_test = train_test_split(predictors, target, random_state=123)
predictors_train.head()

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
PassengerId,,,,,,,,,
87,3.0,1.0,16.0,1.0,3.0,34.375,0.0,0.0,1.0
185,3.0,0.0,4.0,0.0,2.0,22.025,0.0,0.0,1.0
407,3.0,1.0,51.0,0.0,0.0,7.75,0.0,0.0,1.0
286,3.0,1.0,33.0,0.0,0.0,8.6625,1.0,0.0,0.0
592,1.0,0.0,52.0,1.0,0.0,78.2667,1.0,0.0,0.0

In [17]:
target_test.head()

             Survived
PassengerId
652               1.0
695               0.0
798               1.0
876               1.0
506               0.0

### Decision Tree classifier

In [22]:
model = tree.DecisionTreeClassifier(max_leaf_nodes=5, max_depth=5)
model.fit(predictors_train, target_train)

DecisionTreeClassifier(max_depth=5, max_leaf_nodes=5)

### Stochastic gradient descent

In [72]:
model = SGDClassifier("log_loss",verbose=True, early_stopping=False, shuffle=True, random_state=5, learning_rate="adaptive")
model.fit(predictors_train, target_train)

-- Epoch 1
Norm: 1.78, NNZs: 9, Bias: -0.176428, T: 535, Avg. loss: 11.627051, Objective: 11.627195
Total training time: 0.00 seconds.
-- Epoch 2
Norm: 2.55, NNZs: 9, Bias: -0.205855, T: 1070, Avg. loss: 9.078014, Objective: 9.078201
Total training time: 0.00 seconds.
-- Epoch 3
Norm: 3.41, NNZs: 9, Bias: -0.311691, T: 1605, Avg. loss: 11.756639, Objective: 11.757024
Total training time: 0.00 seconds.
-- Epoch 4
Norm: 3.44, NNZs: 9, Bias: -0.228853, T: 2140, Avg. loss: 11.107044, Objective: 11.107618
Total training time: 0.00 seconds.
-- Epoch 5
Norm: 3.99, NNZs: 9, Bias: -0.196392, T: 2675, Avg. loss: 9.083111, Objective: 9.083829
Total training time: 0.00 seconds.
-- Epoch 6
Norm: 4.14, NNZs: 9, Bias: -0.073654, T: 3210, Avg. loss: 8.181639, Objective: 8.182437
Total training time: 0.00 seconds.
-- Epoch 7
Norm: 4.47, NNZs: 9, Bias: -0.017496, T: 3745, Avg. loss: 7.637908, Objective: 7.638795
Total training time: 0.00 seconds.
-- Epoch 8
Norm: 4.95, NNZs: 9, Bias: 0.066983, T: 4280, Avg. loss: 9.649868, Objective: 9.650995
Total training time: 0.00 seconds.
-- Epoch 9
Norm: 5.31, NNZs: 9, Bias: 0.147200, T: 4815, Avg. loss: 9.652938, Objective: 9.654323
Total training time: 0.00 seconds.
-- Epoch 10
Norm: 6.06, NNZs: 9, Bias: 0.198284, T: 5350, Avg. loss: 10.727593, Objective: 10.729262
Total training time: 0.00 seconds.
-- Epoch 11
Norm: 6.73, NNZs: 9, Bias: 0.208908, T: 5885, Avg. loss: 10.307184, Objective: 10.309061
Total training time: 0.00 seconds.
-- Epoch 12
Norm: 6.85, NNZs: 9, Bias: 0.245062, T: 6420, Avg. loss: 13.438888, Objective: 13.441227
Total training time: 0.00 seconds.
-- Epoch 13
Norm: 6.76, NNZs: 9, Bias: 0.295418, T: 6955, Avg. loss: 1.669766, Objective: 1.672075
Total training time: 0.00 seconds.
-- Epoch 14
Norm: 6.71, NNZs: 9, Bias: 0.346427, T: 7490, Avg. loss: 1.658585, Objective: 1.660855
Total training time: 0.00 seconds.
-- Epoch 15
Norm: 6.66, NNZs: 9, Bias: 0.392690, T: 8025, Avg. loss: 1.608216, Objective: 1.610444
Total training time: 0.00 seconds.
-- Epoch 16
Norm: 6.66, NNZs: 9, Bias: 0.418664, T: 8560, Avg. loss: 2.228291, Objective: 2.230505
Total training time: 0.00 seconds.
-- Epoch 17
Norm: 6.61, NNZs: 9, Bias: 0.460993, T: 9095, Avg. loss: 1.583358, Objective: 1.585551
Total training time: 0.00 seconds.
-- Epoch 18
Norm: 6.57, NNZs: 9, Bias: 0.497780, T: 9630, Avg. loss: 1.441873, Objective: 1.444043
Total training time: 0.00 seconds.
-- Epoch 19
Norm: 6.51, NNZs: 9, Bias: 0.536889, T: 10165, Avg. loss: 1.362331, Objective: 1.364470
Total training time: 0.00 seconds.
-- Epoch 20
Norm: 6.49, NNZs: 9, Bias: 0.575180, T: 10700, Avg. loss: 1.592753, Objective: 1.594867
Total training time: 0.00 seconds.
-- Epoch 21
Norm: 6.45, NNZs: 9, Bias: 0.595755, T: 11235, Avg. loss: 1.761919, Objective: 1.764010
Total training time: 0.00 seconds.
-- Epoch 22
Norm: 6.42, NNZs: 9, Bias: 0.626448, T: 11770, Avg. loss: 1.281379, Objective: 1.283453
Total training time: 0.00 seconds.
-- Epoch 23
Norm: 6.40, NNZs: 9, Bias: 0.650686, T: 12305, Avg. loss: 1.373936, Objective: 1.375993
Total training time: 0.00 seconds.
-- Epoch 24
Norm: 6.38, NNZs: 9, Bias: 0.671518, T: 12840, Avg. loss: 1.754678, Objective: 1.756716
Total training time: 0.00 seconds.
-- Epoch 25
Norm: 6.36, NNZs: 9, Bias: 0.685017, T: 13375, Avg. loss: 2.006900, Objective: 2.008930
Total training time: 0.00 seconds.
-- Epoch 26
Norm: 6.33, NNZs: 9, Bias: 0.710074, T: 13910, Avg. loss: 1.720646, Objective: 1.722655
Total training time: 0.00 seconds.
-- Epoch 27
Norm: 6.30, NNZs: 9, Bias: 0.730648, T: 14445, Avg. loss: 1.270479, Objective: 1.272474
Total training time: 0.00 seconds.
-- Epoch 28
Norm: 6.29, NNZs: 9, Bias: 0.743089, T: 14980, Avg. loss: 1.680657, Objective: 1.682640
Total training time: 0.00 seconds.
-- Epoch 29
Norm: 6.25, NNZs: 9, Bias: 0.766366, T: 15515, Avg. loss: 1.657546, Objective: 1.659511
Total training time: 0.00 seconds.
-- Epoch 30
Norm: 6.26, NNZs: 9, Bias: 0.774605, T: 16050, Avg. loss: 1.588928, Objective: 1.590880
Total training time: 0.00 seconds.
-- Epoch 31
Norm: 6.24, NNZs: 9, Bias: 0.789713, T: 16585, Avg. loss: 1.499056, Objective: 1.501008
Total training time: 0.00 seconds.
-- Epoch 32
Norm: 6.24, NNZs: 9, Bias: 0.795216, T: 17120, Avg. loss: 1.955348, Objective: 1.957297
Total training time: 0.00 seconds.
-- Epoch 33
Norm: 6.23, NNZs: 9, Bias: 0.801045, T: 17655, Avg. loss: 0.822376, Objective: 0.824320
Total training time: 0.00 seconds.
-- Epoch 34
Norm: 6.21, NNZs: 9, Bias: 0.806012, T: 18190, Avg. loss: 0.800919, Objective: 0.802853
Total training time: 0.00 seconds.
-- Epoch 35
Norm: 6.20, NNZs: 9, Bias: 0.807766, T: 18725, Avg. loss: 0.801541, Objective: 0.803467
Total training time: 0.00 seconds.
-- Epoch 36
Norm: 6.19, NNZs: 9, Bias: 0.812675, T: 19260, Avg. loss: 0.786367, Objective: 0.788285
Total training time: 0.00 seconds.
-- Epoch 37
Norm: 6.17, NNZs: 9, Bias: 0.815037, T: 19795, Avg. loss: 0.841875, Objective: 0.843785
Total training time: 0.00 seconds.
-- Epoch 38
Norm: 6.16, NNZs: 9, Bias: 0.818778, T: 20330, Avg. loss: 0.850143, Objective: 0.852046
Total training time: 0.00 seconds.
-- Epoch 39
Norm: 6.15, NNZs: 9, Bias: 0.822914, T: 20865, Avg. loss: 0.756593, Objective: 0.758488
Total training time: 0.00 seconds.
-- Epoch 40
Norm: 6.14, NNZs: 9, Bias: 0.825973, T: 21400, Avg. loss: 0.828304, Objective: 0.830191
Total training time: 0.00 seconds.
-- Epoch 41
Norm: 6.13, NNZs: 9, Bias: 0.829673, T: 21935, Avg. loss: 0.821836, Objective: 0.823716
Total training time: 0.00 seconds.
-- Epoch 42
Norm: 6.11, NNZs: 9, Bias: 0.832443, T: 22470, Avg. loss: 0.763813, Objective: 0.765685
Total training time: 0.00 seconds.
-- Epoch 43
Norm: 6.10, NNZs: 9, Bias: 0.836055, T: 23005, Avg. loss: 0.764093, Objective: 0.765959
Total training time: 0.00 seconds.
-- Epoch 44
Norm: 6.09, NNZs: 9, Bias: 0.839359, T: 23540, Avg. loss: 0.765107, Objective: 0.766964
Total training time: 0.00 seconds.
-- Epoch 45
Norm: 6.09, NNZs: 9, Bias: 0.840534, T: 24075, Avg. loss: 0.702975, Objective: 0.704828
Total training time: 0.00 seconds.
-- Epoch 46
Norm: 6.08, NNZs: 9, Bias: 0.841101, T: 24610, Avg. loss: 0.693020, Objective: 0.694871
Total training time: 0.00 seconds.
-- Epoch 47
Norm: 6.08, NNZs: 9, Bias: 0.841660, T: 25145, Avg. loss: 0.674697, Objective: 0.676546
Total training time: 0.00 seconds.
-- Epoch 48
Norm: 6.08, NNZs: 9, Bias: 0.842879, T: 25680, Avg. loss: 0.696826, Objective: 0.698673
Total training time: 0.00 seconds.
-- Epoch 49
Norm: 6.07, NNZs: 9, Bias: 0.843524, T: 26215, Avg. loss: 0.696020, Objective: 0.697865
Total training time: 0.00 seconds.
-- Epoch 50
Norm: 6.07, NNZs: 9, Bias: 0.844521, T: 26750, Avg. loss: 0.696099, Objective: 0.697943
Total training time: 0.00 seconds.
-- Epoch 51
Norm: 6.07, NNZs: 9, Bias: 0.845116, T: 27285, Avg. loss: 0.703069, Objective: 0.704911
Total training time: 0.00 seconds.
-- Epoch 52
Norm: 6.06, NNZs: 9, Bias: 0.845629, T: 27820, Avg. loss: 0.683992, Objective: 0.685832
Total training time: 0.00 seconds.
-- Epoch 53
Norm: 6.06, NNZs: 9, Bias: 0.845944, T: 28355, Avg. loss: 0.679403, Objective: 0.681242
Total training time: 0.00 seconds.
-- Epoch 54
Norm: 6.06, NNZs: 9, Bias: 0.846145, T: 28890, Avg. loss: 0.677474, Objective: 0.679312
Total training time: 0.00 seconds.
-- Epoch 55
Norm: 6.06, NNZs: 9, Bias: 0.846384, T: 29425, Avg. loss: 0.675739, Objective: 0.677577
Total training time: 0.00 seconds.
-- Epoch 56
Norm: 6.06, NNZs: 9, Bias: 0.846491, T: 29960, Avg. loss: 0.676815, Objective: 0.678652
Total training time: 0.00 seconds.
-- Epoch 57
Norm: 6.06, NNZs: 9, Bias: 0.846622, T: 30495, Avg. loss: 0.676290, Objective: 0.678127
Total training time: 0.00 seconds.
-- Epoch 58
Norm: 6.06, NNZs: 9, Bias: 0.846669, T: 31030, Avg. loss: 0.671849, Objective: 0.673685
Total training time: 0.00 seconds.
-- Epoch 59
Norm: 6.06, NNZs: 9, Bias: 0.846704, T: 31565, Avg. loss: 0.671725, Objective: 0.673562
Total training time: 0.00 seconds.
-- Epoch 60
Norm: 6.06, NNZs: 9, Bias: 0.846740, T: 32100, Avg. loss: 0.671657, Objective: 0.673494
Total training time: 0.00 seconds.
-- Epoch 61
Norm: 6.06, NNZs: 9, Bias: 0.846777, T: 32635, Avg. loss: 0.671530, Objective: 0.673366
Total training time: 0.00 seconds.
-- Epoch 62
Norm: 6.06, NNZs: 9, Bias: 0.846807, T: 33170, Avg. loss: 0.671493, Objective: 0.673329
Total training time: 0.00 seconds.
-- Epoch 63
Norm: 6.06, NNZs: 9, Bias: 0.846840, T: 33705, Avg. loss: 0.671498, Objective: 0.673334
Total training time: 0.00 seconds.
-- Epoch 64
Norm: 6.06, NNZs: 9, Bias: 0.846847, T: 34240, Avg. loss: 0.670473, Objective: 0.672310
Total training time: 0.00 seconds.
-- Epoch 65
Norm: 6.06, NNZs: 9, Bias: 0.846853, T: 34775, Avg. loss: 0.670470, Objective: 0.672306
Total training time: 0.00 seconds.
-- Epoch 66
Norm: 6.06, NNZs: 9, Bias: 0.846860, T: 35310, Avg. loss: 0.670465, Objective: 0.672302
Total training time: 0.00 seconds.
-- Epoch 67
Norm: 6.06, NNZs: 9, Bias: 0.846866, T: 35845, Avg. loss: 0.670459, Objective: 0.672296
Total training time: 0.01 seconds.
-- Epoch 68
Norm: 6.06, NNZs: 9, Bias: 0.846872, T: 36380, Avg. loss: 0.670443, Objective: 0.672279
Total training time: 0.01 seconds.
-- Epoch 69
Norm: 6.06, NNZs: 9, Bias: 0.846879, T: 36915, Avg. loss: 0.670444, Objective: 0.672281
Total training time: 0.01 seconds.
Convergence after 69 epochs took 0.01 seconds

/Users/jgrguric/Repos/ml_tut/ML-101/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SGDClassifier(learning_rate='adaptive', loss='log_loss', random_state=5,
              verbose=True)

### Accuracy

In [58]:
target_test.iloc[:, 0]
# predictors_test.iloc[1, :]

PassengerId
652    1.0
695    0.0
798    1.0
876    1.0
506    0.0
      ...
131    0.0
875    1.0
377    1.0
821    1.0
487    1.0
Name: Survived, Length: 179, dtype: Float64

In [64]:
# predictions = np.zeros(predictions.shape, np.float64)
predictions = model.predict(predictors_test)

In [68]:
predictions

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0.,
       0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 1., 1.])

In [69]:
n = 0
correct = 0
for prediction in predictions:
    correct += int(prediction==target_test.iloc[n, 0])
    n += 1

print("Accuracy rate: ", (correct)/n)
print("Total number of guesses: ", n)

Accuracy rate:  0.7932960893854749
Total number of guesses:  179

In [70]:
true_positive = 0
true_negative = 0
false_positive = 0
false_negative = 0
predictions = clf.predict(predictors_test)

for i, prediction in enumerate(predictions):
    if prediction == target_test.iloc[i, 0]:
        if prediction:
            true_positive += 1
        else:
            true_negative += 1
    else:
        if prediction:
            false_positive += 1
        else:
            false_negative += 1

print("Accuracy rate: ", (correct)/n)
print("Total number of guesses: ", n)
print("Confusion matrix:")
print(f"True positive: {true_positive} \t False negative: {false_negative}")
print(f"False positive: {false_positive} \t True negative: {true_negative}")

Accuracy rate:  0.7932960893854749
Total number of guesses:  179
Confusion matrix:
True positive: 35 	 False negative: 36
False positive: 1 	 True negative: 107